model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModelRetrainable
  params:
    embed_dim: 8
    n_embed: 16384
    ddconfig:
      double_z: false
      z_channels: 8
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.75
        disc_num_layers: 2
        codebook_weight: 1.0
    ckpt_path: "./models/first_stage_models/vq-f16/model.ckpt"
    target_transformation_fn:
      target: ldm.modules.autoencoder_transformations.Invert

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 12
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetSRTrain
      params:
        size: 256
        degradation: pil_nearest
    validation:
      target: ldm.data.imagenet.ImageNetSRValidation
      params:
        size: 256
        degradation: pil_nearest

#lightning:
  #modelcheckpoint: 
    #target: pytorch_lightning.callbacks.ModelCheckpoint
    #params:
      #dirpath: "models/first_stage_models/vq-f16/"
      #filename: "model.ckpt"
      #verbose: true
      #save_last: true

